objects/Inventory__c.object
<CustomObject><fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instrumentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laparoscopes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disposable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Preference_Card__c</fullName>
        <label>Preference Card</label>
        <referenceTo>Preference_Card__c</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Inventory</label><nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Inventories</pluralLabel><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/Opportunity.object
<CustomObject><fields>
        <fullName>Preference_Card__c</fullName>
        <formula>HYPERLINK("https://surgicalsolutions.my.salesforce.com/apex/PreferenceCard?oppId=00641000005Qjz2&amp;pcId=a3z410000005TCP", "Preference Card")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Preference Card</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Surgeon__c</fullName>
        <label>Surgeon</label>
        <length>30</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Preference_Card__c.object
<CustomObject><fields>
        <fullName>Arms__c</fullName>
        <label>Arms</label>
        <picklist>
            <picklistValues>
                <fullName>Arms Option #1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arms Option #2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arms Option #3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arms Option #4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arms Option #5</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Legs__c</fullName>
        <label>Legs</label>
        <picklist>
            <picklistValues>
                <fullName>Legs Option #1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legs Option #2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legs Option #3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legs Option #4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legs Option #5</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Normal__c</fullName>
        <label>Normal</label>
        <picklist>
            <picklistValues>
                <fullName>Normal Option #1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal Option #2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal Option #3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal Option #4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal Option #5</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Patient_Position__c</fullName>
        <label>Patient Position</label>
        <picklist>
            <picklistValues>
                <fullName>Position #1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Position #2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Position #3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Position #4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Position #5</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Room_Setup__c</fullName>
        <label>Room Setup</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>Stirrups__c</fullName>
        <label>Stirrups</label>
        <picklist>
            <picklistValues>
                <fullName>Stirrops Option #1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stirrops Option #2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stirrops Option #3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stirrops Option #4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stirrops Option #5</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Surgeon__c</fullName>
        <label>Surgeon</label>
        <length>30</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Preference Card</label><nameField>
        <label>Preference Card Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Preference Cards</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/PreferenceCard.cls
public class PreferenceCard {
	
	@AuraEnabled
	public static Opportunity getOppById(String theId)
	{
		Opportunity theOpp = [SELECT Id, StageName, Surgeon__c, Owner.Name FROM Opportunity WHERE Id =: theId];

		return theOpp;
	}

	@AuraEnabled
	public static Preference_Card__c getPreferenceCardById(String theId)
	{
		Preference_Card__c thePreferenceCard = [SELECT Id, Legs__c, Arms__c, Patient_Position__c, Room_Setup__c,Stirrups__c, Normal__c FROM Preference_Card__c WHERE Id =: theId];

		return thePreferenceCard;
	}

	@AuraEnabled
	public static Map<String,List<Inventory__c>> getInventories(String theId)
	{
		Map<String,List<Inventory__c>> theMap = new Map<String,List<Inventory__c>>();

		List<Inventory__c> listOfInventory = [SELECT Id, Name, Category__c, Quantity__c FROM Inventory__c WHERE Preference_Card__c =: theId];
		
		for(Inventory__c theInv : listOfInventory)
		{
			if(!theMap.containsKey(theInv.Category__c))
			{
				theMap.put(theInv.Category__c,new List<Inventory__c>());
			}

			theMap.get(theInv.Category__c).add(theInv);
		}

		return theMap;
	}
}